### PR TITLE
Use without printer screen

### PR DESCRIPTION
**Pull request by jbrandek**
I would like to use the plugin but my printer screen does not work with M117

It is possible to use it only with octoprint and proceed to each step without the printer screen?

### CODE REVIEW

**Comment by j-be** [comment]
Hi @jbrandek, thanks for the suggestion.

Have you considered using the [M117PopUp plugin](https://plugins.octoprint.org/plugins/M117PopUp/)?

If so, what additional feature are you missing?

**Comment by j-be** [comment]
@jbrandek any news? If not, I'd close this PR.

**Comment by jbrandek** [comment]
> @jbrandek any news? If not, I'd close this PR.

Sorry i didnt see last reply i will try that plugin and let you know

**Comment by jbrandek** [comment]
> Hi @jbrandek, thanks for the suggestion.
> 
> Have you considered using the [M117PopUp plugin](https://plugins.octoprint.org/plugins/M117PopUp/)?
> 
> If so, what additional feature are you missing?

Thanks working perfectly

**Pull request closed without merging**
